export dockertag=jgwill/ubuntu:18.04-py3.7.2-lzma-pto221125
export containertag=ubpy37pto221125


dkbuildprebuildscript=dkbuildprebuildscript.sh
dkbuildbuildsuccessscript=dkbuildbuildsuccessscript.sh
dkbuildfailedscript=dkbuildfailedscript.sh
dkbuildpostbuildscript=dkbuildpostbuildscript.sh
