export dockertag=jgwill/ubuntu:20.04-py3.10.13-lzma-node-latest
export containertag=ubpy310node-latest


dkbuildprebuildscript=dkbuildprebuildscript.sh
dkbuildbuildsuccessscript=dkbuildbuildsuccessscript.sh
dkbuildfailedscript=dkbuildfailedscript.sh
dkbuildpostbuildscript=dkbuildpostbuildscript.sh
