apt remove -y \
dh-python \
libboost-mpi-python-dev \
libboost-mpi-python1.65-dev \
libboost-mpi-python1.65.1 \
libboost-python-dev \
libboost-python1.65-dev \
libboost-python1.65.1 \
libpython-dev \
libpython-stdlib \
libpython2.7 \
libpython2.7-dev \
libpython2.7-minimal \
libpython2.7-stdlib \
libpython3-dev \
libpython3-stdlib \
libpython3.6 \
libpython3.6-dev \
libpython3.6-minimal \
libpython3.6-stdlib \
python \
python-apt-common \
python-dev \
python-minimal \
python2.7 \
python2.7-dev \
python2.7-minimal \
python3 \
python3-apt \
python3-dbus \
python3-dev \
python3-distutils \
python3-gi \
python3-lib2to3 \
python3-minimal \
python3-software-properties \
python3.6 \
python3.6-dev \
python3.6-minimal \
