export dockertag=jgwill/ubuntu:18.04-py3.7.2-lzma-node-tooled
export containertag=ubpy37node16tooled


dkbuildprebuildscript=dkbuildprebuildscript.sh
dkbuildbuildsuccessscript=dkbuildbuildsuccessscript.sh
dkbuildfailedscript=dkbuildfailedscript.sh
dkbuildpostbuildscript=dkbuildpostbuildscript.sh
