FROM jgwill/ubuntu:16.04-py3.7.1

#USER ubuntu

#RUN pip install --upgrade pip
RUN pip3.7 install matplotlib
RUN pip3.7 install pandas

RUN pip3.7 install pyodbc
RUN pip3.7 install scipy
RUN pip3.7 install sklearn

#USER root

