export dockertag=jgwill/ubuntu:22.04
export dockertag1=jgwill/ubuntu
export containername=jgwillubuntu22




dkbuildprebuildscript=dkbuildprebuildscript.sh
dkbuildbuildsuccessscript=dkbuildbuildsuccessscript.sh
dkbuildfailedscript=dkbuildfailedscript.sh
dkbuildpostbuildscript=dkbuildpostbuildscript.sh
